	if (isServer) then {
		mosque = (getMarkerpos "civ_spawnpoint_northcivspawn" nearestobject "Land_A_Mosque_big_hq_EP1");
		mosque1 = (getMarkerpos "civ_spawnpoint_northcivspawn" nearestobject 58479);
		mosque2 = (getMarkerpos "civ_spawnpoint_northcivspawn" nearestobject 58480);
		mosque3 = (getMarkerpos "civ_spawnpoint_northcivspawn" nearestobject 59178);
		mosque4 = (getMarkerpos "civ_spawnpoint_northcivspawn" nearestobject 59182);
		mosque5 = (getMarkerpos "civ_spawnpoint_northcivspawn" nearestobject 59179);
		mosque6 = (getMarkerpos "civ_spawnpoint_northcivspawn" nearestobject 59185);
		mosque7 = (getMarkerpos "civ_spawnpoint_northcivspawn" nearestobject 59184);
		mosque8 = (getMarkerpos "civ_spawnpoint_northcivspawn" nearestobject 59183);
		mosque9 = (getMarkerpos "civ_spawnpoint_northcivspawn" nearestobject 59180);
		mosque10 = (getMarkerpos "civ_spawnpoint_northcivspawn" nearestobject 59181);
		mosque11 = (getMarkerpos "civ_spawnpoint_northcivspawn" nearestobject 58526);
		mosque12 = (getMarkerpos "civ_spawnpoint_northcivspawn" nearestobject 58512);
		mosque13 = (getMarkerpos "civ_spawnpoint_northcivspawn" nearestobject 58512);
		mosque14 = (getMarkerpos "civ_spawnpoint_northcivspawn" nearestobject 58527);
		mosque15 = (getMarkerpos "civ_spawnpoint_northcivspawn" nearestobject 58514);
		mosque16 = (getMarkerpos "civ_spawnpoint_northcivspawn" nearestobject 58513);
		mosque17 = (getMarkerpos "civ_spawnpoint_northcivspawn" nearestobject 59186);
		mosque18 = (getMarkerpos "civ_spawnpoint_northcivspawn" nearestobject 59187);
		mosque19 = (getMarkerpos "civ_spawnpoint_northcivspawn" nearestobject 58499);
		mosque20 = (getMarkerpos "civ_spawnpoint_northcivspawn" nearestobject 58511);
		mosque21 = (getMarkerpos "civ_spawnpoint_northcivspawn" nearestobject 58503);
		tree1 = (getMarkerpos "civ_spawnpoint_northcivspawn" nearestobject 59576);
		
		mosque attachto [mosqueattach, [0,0,0]]; 
		mosque1 attachto [mosqueattach, [0,0,0]]; 
		mosque2 attachto [mosqueattach, [0,0,0]]; 
		mosque3 attachto [mosqueattach, [0,0,0]]; 
		mosque4 attachto [mosqueattach, [0,0,0]]; 
		mosque5 attachto [mosqueattach, [0,0,0]]; 
		mosque6 attachto [mosqueattach, [0,0,0]]; 
		mosque7 attachto [mosqueattach, [0,0,0]]; 
		mosque8 attachto [mosqueattach, [0,0,0]]; 
		mosque9 attachto [mosqueattach, [0,0,0]]; 
		mosque10 attachto [mosqueattach, [0,0,0]]; 
		mosque11 attachto [mosqueattach, [0,0,0]]; 
		mosque12 attachto [mosqueattach, [0,0,0]]; 
		mosque13 attachto [mosqueattach, [0,0,0]]; 
		mosque14 attachto [mosqueattach, [0,0,0]]; 
		mosque15 attachto [mosqueattach, [0,0,0]]; 
		mosque16 attachto [mosqueattach, [0,0,0]]; 
		mosque17 attachto [mosqueattach, [0,0,0]]; 
		mosque18 attachto [mosqueattach, [0,0,0]]; 
		mosque19 attachto [mosqueattach, [0,0,0]]; 
		mosque20 attachto [mosqueattach, [0,0,0]];  
		mosque21 attachto [mosqueattach, [0,0,0]];  
		mosqueattach setPos [getPos mosqueattach select 0, getPos mosqueattach select 1, -500];
	};